### ISSUE TITLE
Compare request

### ISSUE THREAD

**Issue by fhdk** [anydistro/bxt#56]
Related to #22

When a compare request is posted - the request contains a json body with a list of boxes to compare.

```
[
  {
    "branch": "unstable",
    "repository": "core",
    "architecture": "x86_64"
  },
  {
    "branch": "testing",
    "repository": "core",
    "architecture": "x86_64"
  }
]
```

The answer only contains boxes known to the database. A short excerpt

```
{
    "sections":
    [
        {
            "branch": "unstable",
            "repository": "core",
            "architecture": "x86_64"
        }
    ],
    "compareTable":
    {
        "flex":
        {
            "unstable/core/x86_64":
            {
                "sync": "2.6.4-5"
            }
        },
        "logrotate":
        {
            "unstable/core/x86_64":
            {
                "sync": "3.21.0-2"
            }
        }
    }
}
```

Is this result to be expected if a requested box does not exist?

Would it be an empty list if none of the boxes exist?
```
[
  {
    "branch": "stable",
    "repository": "core",
    "architecture": "x86_64"
  },
  {
    "branch": "testing",
    "repository": "core",
    "architecture": "x86_64"
  }
]
```

That one answered itself :grin: 

```
{
    "message": "No compare data found (all sections are empty)",
    "status": "error"
}
```

**Comment by LordTermor** [comment]
> That one answered itself 😁

So the issue is solved?

**Comment by fhdk** [comment]
Not quite sure it is an issue - the initial question still stands.

I kind of expected the compare request to return an an empty entry when a none exist

Comparing unstable and testing - a response along the lines of this was expected
```
{
    "sections":
    [
        {
            "branch": "unstable",
            "repository": "core",
            "architecture": "x86_64"
        },
        {
            "branch": "testing",
            "repository": "core",
            "architecture": "x86_64"
        }
    ],
    "compareTable":
    {
        "flex":
        {
            "unstable/core/x86_64":
            {
                "sync": "2.6.4-5"
            },
            "testing/core/x86_64":
            {
                "sync": ""
            }
        },
        "logrotate":
        {
            "unstable/core/x86_64":
            {
                "sync": "3.21.0-2"
            },
            "testing/core/x86_64":
            {
                "sync": ""
            }
        }
    }
}
```

**Comment by LordTermor** [comment]
Is there a reason to return empty strings for every package out there? 

If package is not in a section, the section will not be in table. The separate "sections" array is needed to check that sections do exist in repository, it's just packages are not there in case there were none packages in a section.

**Comment by fhdk** [comment]
Then it is per design - which was the reason I asked.

Technically - real world - you may have a package in on one box which is not in another.

This goes for a long time repo package which got removed in unstable but still exist in stable or testing or the other way around - a package may exist in unstable but has not yet been moved to testing.

In this case the testing repo didn't have any content - but for the sake of this topic - let's generate an example

- unstable contains all packages including foo.pkg.tar.zst
- testing contains nothing  but the package foo.pkg.tar.zst

How would you list the comparison if you did not include an empty string for each off the packages in unstable which is not present in testing?

Testing contains one package so compared to unstable you would need to create empty strings for all those that do not exist in testing but is in unstable.

**Comment by fhdk** [comment]
@LordTermor @romangg 
Can you provide some extra information - details on how the compare response can be parsed.

I just realized that the property holding the version may be different.

While enum logic is a great method of describing an entity - when parsing the returned data it is impossible to guess what a field describes.

So returning the data in a named structure `"name":"value"` instead of a enum value structure `"value":{"anothervalue":"thirdvalue"}` would be fantastic.

The enums used is undocumented and the connections is therefore next to impossible to understand.

**Comment by LordTermor** [comment]
> It does not make sense that the version value can be located in different property named automated and overlay respectively.

There are different "candidates" (aka locations) of packages. The only problem here is that 

> enumeration which has no documentation

Which is a pretty minor problem.

I'll update the docs. The `location` is one of `overlay`, `sync` or `automated`, any of them can be provided. I should add `preferredCandidate` like with packages though.

> How would you list the comparison if you did not include an empty string for each off the packages in unstable which is not present in testing?

Foo then will be listed in the resulting structure with `testing/core/x86_64` while everything else will have `unstable/core/x86_64`, but the `sections` field will contain both `testing/core/x86_64` and `unstable/core/x86_64`:

_(took your message as an example)_
```json
{
    "sections":
    [
        {
            "branch": "unstable",
            "repository": "core",
            "architecture": "x86_64"
        },
        {
            "branch": "testing",
            "repository": "core",
            "architecture": "x86_64"
        }
    ],
    "compareTable":
    {
        "libb2":
        {
            "unstable/core/x86_64":
            {
                "overlay": "0.98.1-2"
            }
        },
        "abseil-cpp":
        {
            "unstable/core/x86_64":
            {
                "overlay": "20240116.2-2"
            }
        },
        "flex":
        {
            "unstable/core/x86_64":
            {
                "automated": "2.6.4-5"
            }
        },
        "ruby-getoptlong":
        {
            "unstable/core/x86_64":
            {
                "overlay": "0.1.1-3"
            }
        },
        "arch-install-scripts":
        {
            "unstable/core/x86_64":
            {
                "overlay": "28-1"
            }
        },
        "foo":
        {
            "testing/core/x86_64":
            {
                "overlay": "version"
            }
        },
    }
}
```

**Comment by fhdk** [comment]
:white_check_mark:  I will add the possible values to the code.

I have been updating the openapi as well - perhaps I should make a PR with my additions

**Comment by fhdk** [comment]
Just for the record - the property
```
            "testing/core/x86_64":
            {
                "overlay": "version"
            }
```
Is it ever possible that more than one value is provided?
Or is it always - for any one given combination of branch/repo/architeture - one of **overlay**, **sync**, **automated**?

**Comment by LordTermor** [comment]
> Is it ever possible that more than one value is provided?

Yep, if there are multiple candidates all of them will be presented

> I have been updating the openapi as well - perhaps I should make a PR with my additions

Go ahead

**Comment by LordTermor** [comment]
> The CompareResponse documetation is vague
> 
> ```
>     CompareResponse:
>       type: object
>       properties:
>         sections:
>           type: array
>           items:
>             $ref: "#/components/schemas/PackageSection"
>         compareTable:
>           type: object
>           additionalProperties:
>             type: object
>             additionalProperties:
>               type: object
>               additionalProperties:
>                 type: string
> ```
> 
> It would be great to docoment what is what, and what values can one expect, and how they connect in the larger picture.

Sure, I already mentioned that 

> I'll update the docs

previously

**Comment by fhdk** [comment]
This issue only clutters the list - I will work with it - aks again if necessary
